image: microsoft/dotnet:latest

stages:
  - build
  - deploy

variables:
  project: "BPOSolution"

before_script:
  - "dotnet restore"

build_job:
  stage: build
  only:
    - branches
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"
  artifacts:
    paths: 
    - '$project/bin/Release/Publish/'
  
deploy_job:
  stage: deploy
  only:
    - branches
  script: 
    - 'xcopy /y /s "$project/bin/Release/Publish/*.*" "https://Devpartners.co/Inventory/api/"'

dependencies:
  - build_job
