image: microsoft/dotnet:latest

stages:
  - build
  - deploy

variables:
  project: "Portfolio"

before_script:
  - "dotnet restore"

build_job:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"
  artifacts:
    paths: 
    - '$project/bin/Release/Publish/'
  
# deploy_job:
#   stage: deploy
#   only:
#   - master
#   script: 
#     - 'xcopy /y /s "$project/bin/Release/Publish/*.*" "https://Devpartners.co/Inventory/api/"'

#     - 'curl -X POST -u https://Devpartners.co/Inventory/api/'

deploy_job:
stage: deploy
script:
  - echo "Deploy to  server"
environment:
  stage: deploy
  url: https://Devpartners.co/Inventory/api/
only:
- master
