image: microsoft/dotnet:latest

stages:
  - build
  - deploy

variables:
  project: "Portfolio"

before_script:
  - "dotnet restore"

# deploy:
#   stage: deploy
#   variables:
#     build_path: "$project"
#   script:
#     - echo "Deploy to Prod"
#     - "cd $build_path"
#     - "dotnet build"
#     - "dotnet publish"
#   environment:
#     name: production
#     url: https://Devpartners.co/Inventory/api/
#   only:
#   - master

build_job:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"
    - "dotnet publish"
  artifacts:
    paths: 
    - '$project/bin/Release/Publish/'
  
deploy_job:
  stage: deploy
  only:
  - master
  script: 
    - 'xcopy /y /s "/builds/mlabio/BPOSolution/Portfolio/bin/Debug/netcoreapp2.1/*.*" "https://Devpartners.co/Inventory/api/"'
