build:
  stage: build
  script:
    - chmod +x run.sh clean.sh
    - bash run.sh
    - docker build -t dockertest .
    - docker run -d -p /dummy/api/ --restart unless-stopped dockertest
    - bash clean.sh
  environment:
    name: production
    url: https://devpartners.co/dummy/api/