image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy
  
before_script:
  - "dotnet restore" 
  
build:
  stage: build
  script:
    - dotnet build

deploy:
  stage: deploy
  script:
    - BPOSolution/publish.cmd
  #  - ssh 40.65.191.64 "cd \inetpub\wwwroot\dummy\BackEnd" && git checkout master && git pull origin master && exit"
  environment:
    name: production
    url: https://devpartners.co/dummy/api/api/values
  only:
    - master