image: microsoft/dotnet:latest

variables: 
  project: "Portfolio"

before_script:
  - "dotnet restore"

build:
  stage: build
  script: 
    - echo "Deploy to Prod"
    - cd $build_path
    - "dotnet build"
  environment: 
    name: production
    url: https://devpartners.co/dummy/api/
